export const defaultValues = [
  {name: 'pikachu',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/25.svg',
    baseCost: 10,
    baseIncrease: 1,
    pokyMultiplier: 2,
    costMultiplier: 3,
    isPerSecond: false,
  },
  {name: 'bulbasaur',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg',
    baseCost: 200,
    baseIncrease: 2,
    pokyMultiplier: 2,
    costMultiplier: 3,
    isPerSecond: false,
  },
  {name: 'charmander',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/4.svg',
    baseCost: 500,
    baseIncrease: 5,
    pokyMultiplier: 2,
    costMultiplier: 3,
    isPerSecond: false,
  },
  {name: 'squirtle',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/7.svg',
    baseCost: 10000,
    baseIncrease: 10,
    pokyMultiplier: 2,
    costMultiplier: 3,
    isPerSecond: false,
  },
  {name: 'great-ball',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/great-ball.png',
    baseCost: 10000,
    baseIncrease: 10,
    pokyMultiplier: 2,
    costMultiplier: 3,
    isPerSecond: true,
  },
]